name: Deploy site on main

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - run: npm install
    - run: npm run build
    - name: Deploy site to gh-pages branch
      uses: alex-page/blazing-fast-gh-pages-deploy@main
      with:
        repo-token: ${{ secrets.GH_PAT }}